### ISSUE TITLE
Can't start Deebot 711s but stop it

### ISSUE THREAD

**Issue by bryanbrannigan** [nicoduj/homebridge-deebotEcovacs#40]
I have a 711s and a 79s. The 79s (Connor) works fine. The 711s (Dylan) won't start. When I try to start it I get a cleaning status of undefined. If I start the 711s from the Ecovacs app I get a good status in homebridge. And if the vac is running I can turn it off and it returns to charge. 

`[11/14/2020, 4:07:00 PM] [DeebotEcovacs] INFO - Clean status for Connor : stop
[11/14/2020, 4:07:00 PM] [DeebotEcovacs] INFO - Battery level for Connor : 100 100 0
[11/14/2020, 4:07:00 PM] [DeebotEcovacs] INFO - Charge status for Connor : charging false true
[11/14/2020, 4:07:09 PM] [DeebotEcovacs] INFO - getDeebotEcovacsOnCharacteristic for Connor
[11/14/2020, 4:07:09 PM] [DeebotEcovacs] INFO - getDeebotEcovacsSpeedCharacteristic for Connor
[11/14/2020, 4:07:09 PM] [DeebotEcovacs] INFO - getDeebotEcovacsOnCharacteristic for Connor
[11/14/2020, 4:07:09 PM] [DeebotEcovacs] INFO - getLowBatteryCharacteristic for Connor
[11/14/2020, 4:07:09 PM] [DeebotEcovacs] INFO - getDeebotEcovacsOnCharacteristic for Dylan
[11/14/2020, 4:07:09 PM] [DeebotEcovacs] INFO - getLowBatteryCharacteristic for Dylan
[11/14/2020, 4:07:09 PM] [DeebotEcovacs] INFO - getDeebotEcovacsSpeedCharacteristic for Dylan
[11/14/2020, 4:07:09 PM] [DeebotEcovacs] INFO - getDeebotEcovacsOnCharacteristic for Dylan
[11/14/2020, 4:07:10 PM] [DeebotEcovacs] INFO - Clean status for Connor : stop
[11/14/2020, 4:07:10 PM] [DeebotEcovacs] INFO - Charge status for Connor : charging false true
[11/14/2020, 4:07:11 PM] [DeebotEcovacs] INFO - Clean status for Dylan : stop
[11/14/2020, 4:07:11 PM] [DeebotEcovacs] INFO - Charge status for Dylan : charging false true
[11/14/2020, 4:07:11 PM] [DeebotEcovacs] INFO - Charge status for Dylan : charging false true
[11/14/2020, 4:07:11 PM] [DeebotEcovacs] INFO - Clean status for Dylan : stop
[11/14/2020, 4:07:11 PM] [DeebotEcovacs] INFO - Clean status for Connor : stop
[11/14/2020, 4:07:11 PM] [DeebotEcovacs] INFO - Charge status for Connor : charging false true
[11/14/2020, 4:07:17 PM] [DeebotEcovacs] INFO - setDeebotEcovacsOnCharacteristic for Dylan-true-false-Clean,auto
[11/14/2020, 4:07:18 PM] [DeebotEcovacs] INFO - Clean status for Dylan : undefined
[11/14/2020, 4:07:21 PM] [DeebotEcovacs] INFO - setDeebotEcovacsOnCharacteristic for Dylan-true-false-Clean,auto
[11/14/2020, 4:07:22 PM] [DeebotEcovacs] INFO - Clean status for Dylan : undefined
`

**Comment by nicoduj** [comment]
Hi, did you try any other mode (edge maybe ? )

**Comment by bryanbrannigan** [comment]
@nicoduj Edge also does not work
`Nov 14 17:33:00 raspberrypi homebridge[24196]: [11/14/2020, 5:33:00 PM] [DeebotEcovacs] INFO - setDeebotEcovacsOrderCharacteristic for Dylan-Edge
Nov 14 17:33:01 raspberrypi homebridge[24196]: [11/14/2020, 5:33:01 PM] [DeebotEcovacs] INFO - Clean status for Dylan : undefined`

**Comment by nicoduj** [comment]
can you ask on the repo of the lib if this model is ok, linking this issue ? : https://github.com/mrbungle64/ecovacs-deebot.js/issues

**Comment by nicoduj** [comment]
An by the way, since you have 2 deebots, do you experience this issue also : Using two DeebotSlim with the plugin #37 ?

**Comment by nicoduj** [comment]
From whar I see support of 711 might not be full : The "pause" button does not work with Deebot 710/711.

**Comment by mrbungle64** [comment]
@nicoduj @eightzerobits 

The Deebot 710/711 should work except the "pause" command.
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/37 (German language only)
I originally developed the deebot-ecovacs.js library for this [ioBroker Adapter](https://github.com/mrbungle64/ioBroker.ecovacs-deebot).

I'm not 100% sure if it's still working with Deebot 710/711 but since March there are no reports that it's not the case anymore.

> can you ask on the repo of the lib if this model is ok, linking this issue ? : https://github.com/mrbungle64/ecovacs-deebot.js/issues

You can of course create an issue for that problem so that we can investigate this case.

**Comment by nicoduj** [comment]
@mrbungle64 Thanks, strange but might be linked to #37 . By the way, do you have any idea why I would receive events for both deebots in case of multiple ones ? It seems that both vacBot objects receive events for both deebots ... might be on my side however, but can't put the finger on it (and can't test since I have only one)

**Comment by mrbungle64** [comment]
> @mrbungle64 Thanks, strange but might be linked to #37 . By the way, do you have any idea why I would receive events for both deebots in case of multiple ones ? It seems that both vacBot objects receive events for both deebots ... might be on my side however, but can't put the finger on it (and can't test since I have only one)

@nicoduj 
It's a bit tricky to run multiple devices at once...

In [ioBroker](https://www.iobroker.net/) you can create multiple instances.
One for each device. Each device therefore has its own scope.

Some weeks ago I also startet working on a [Node-RED node](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot) and I experience also some weird behaviour running multiple devices at once. I also receive some events for all devices at once. But to be honest I haven't spent much time on solving that problem yet.

In ioBroker I'm using 3 Ecovacs devices
* Deebot 900/901 (MQTT)
* Deebot Ozmo 930 (XMPP)
* For testing only: Deebot Slim 2 (XMPP)

If I start 2 (901 and 1 of the XMPP devices) or all 3 instances at once the Deebot 900/901 instance stops working once one of the XMPP based device connected.
Because of this behaviour I have to start the XMPP devices first until I can start the MQTT device instance. If I start that devices in this order it's working fine.

@eightzerobits 
As far as I remember the Deebot 711 is MQTT based but the N79S is XMPP based.
So you have to start that devices also in this order. But I asume that it's not working because they are running in the same instance.

@nicoduj  @eightzerobits 
Is it maybe possible to create multiple instances of a plugin?

**Comment by mrbungle64** [comment]
> As far as I remember the Deebot 711 is MQTT based but the N79S is XMPP based.
> So you have to start that devices also in this order. But I asume that it's not working because they are running in the same instance.

@eightzerobits 
Can you please remove/disable the N79S in homebridge-deebotEcovacs to see if the Deebot 711 is working?

@nicoduj 
Is it possible to remove/disable single devices?

**Comment by nicoduj** [comment]
@mrbungle64 Hi, thanks for clarification, I was becoming to loose my mind on this :p There is still the capacity to declare multiple instance in homebridge yes, BUT i will need to add something to only use one device per instance (my plugin is looping through discovered deebots). Will work on it to see if it solves thoses problems at first, before trying to make them work together :)

**Comment by nicoduj** [comment]
@eightzerobits : so I published a new version where you should be able to publish each on a different platform. Let us know !

**Comment by bryanbrannigan** [comment]
I updated and updated my config.json to have both robots. Unfortunately now it only shows me one of them. I did a clearCache and then it showed me the other one, but only one at a time. Depending on which vac is showing I still get the same behavior. The 79s will start but the 711s will not. The 711s will respond to the Big switch.

**Comment by mrbungle64** [comment]
@eightzerobits 

Can you please install [this library](https://github.com/mrbungle64/ecovacs-deebot.js)?
So that we can see if the library (still) handles the Deebot 711 correctly.

1)
```bash
git clone https://github.com/mrbungle64/ecovacs-deebot.js.git
cd ecovacs-deebot.js
npm install
cd example
```

2) in the file `app2.js`

- change email, password and country code
- and in line 20 `let vacuum = devices[0];` you have to use the number of your Deebot 711 (should be `0` or  `1`)

3) execute the example app and the device should start cleaning. If not please post the output. But please be careful because it may contain sensitive data.

**Comment by bryanbrannigan** [comment]
It would seem the library does not support the 711s.

`na
{ did: 'b920e9a0-03f6-4de0-9de8-566edb39a82c',
  name: 'E2000771991902701316',
  class: 'd0cnel',
  resource: 'fGQl',
  nick: 'Dylan',
  company: 'eco-ng',
  bindTs: 1604529358965 }
[app2.js] isKnownDevice: false
[app2.js] isSupportedDevice: false
[app2.js] name: false
[app2.js] hasMainBrush: false
[app2.js] hasSpotAreas: false
[app2.js] hasCustomAreas: false
[app2.js] hasMoppingSystem: false
[app2.js] hasVoiceReports: false
vacbot ready
[app2.js] CleanReport: undefined
[app2.js] filter: 85
[app2.js] side_brush: 88
[app2.js] main_brush: 94
[app2.js] Error: Request Timeout
[app2.js] Error: NoError: Robot is operational
[app2.js] CleanReport: stop
[app2.js] water level: 2
[app2.js] ChargeState: charging
[app2.js] BatteryInfo: 61
[app2.js] ChargeState: charging
[app2.js] CleanReport: stop
[app2.js] water level: 2
[app2.js] BatteryInfo: 61
`

**Comment by mrbungle64** [comment]
> It would seem the library does not support the 711s.
> 
> `na { did: 'b920e9a0-03f6-4de0-9de8-566edb39a82c', name: 'E2000771991902701316', class: 'd0cnel', resource: 'fGQl', nick: 'Dylan', company: 'eco-ng', bindTs: 1604529358965 } [app2.js] isKnownDevice: false [app2.js] isSupportedDevice: false [app2.js] name: false [app2.js] hasMainBrush: false [app2.js] hasSpotAreas: false [app2.js] hasCustomAreas: false [app2.js] hasMoppingSystem: false [app2.js] hasVoiceReports: false vacbot ready [app2.js] CleanReport: undefined [app2.js] filter: 85 [app2.js] side_brush: 88 [app2.js] main_brush: 94 [app2.js] Error: Request Timeout [app2.js] Error: NoError: Robot is operational [app2.js] CleanReport: stop [app2.js] water level: 2 [app2.js] ChargeState: charging [app2.js] BatteryInfo: 61 [app2.js] ChargeState: charging [app2.js] CleanReport: stop [app2.js] water level: 2 [app2.js] BatteryInfo: 61 `

@eightzerobits
Sorry, I didn't recognize the "s" in "711s" before ... 711 and 711s are different models.

Did the device start cleaning?

Btw: The battery value, water level, consumable values seem to be correct.

**Comment by bryanbrannigan** [comment]
No it did not start cleaning. I switched the device value and the 79s did start cleaning.

**Comment by mrbungle64** [comment]
@eightzerobits 

Can you please delete line 44 in the file `library/vacBotCommand_non950type.js` and try again?

delete => `'speed': constants_type.FAN_SPEED_TO_ECOVACS['normal'],`

line 42-45 should be:

```javascript
let initCmd = {
    'type': constants_type.CLEAN_MODE_TO_ECOVACS[mode],
    'act': constants_type.CLEAN_ACTION_TO_ECOVACS[action]
 };
```

**Comment by bryanbrannigan** [comment]
No change
`na
{ did: 'b920e9a0-03f6-4de0-9de8-566edb39a82c',
  name: 'E2000771991902701316',
  class: 'd0cnel',
  resource: 'fGQl',
  nick: 'Dylan',
  company: 'eco-ng',
  bindTs: 1604529358965 }
[app2.js] isKnownDevice: false
[app2.js] isSupportedDevice: false
[app2.js] name: false
[app2.js] hasMainBrush: false
[app2.js] hasSpotAreas: false
[app2.js] hasCustomAreas: false
[app2.js] hasMoppingSystem: false
[app2.js] hasVoiceReports: false
vacbot ready
[app2.js] main_brush: 94
[app2.js] side_brush: 88
[app2.js] CleanReport: undefined
[app2.js] filter: 85
[app2.js] Error: Request Timeout
[app2.js] Error: NoError: Robot is operational
[app2.js] CleanReport: stop
[app2.js] ChargeState: charging
[app2.js] water level: 2
[app2.js] BatteryInfo: 68
`

**Comment by mrbungle64** [comment]
@eightzerobits 

Can you please execute the example app using the follwing command:

```
NODE_ENV=dev node app2.js | grep 'xml received'
```

Wait for maybe 30 sec. and post the output please :)

**Comment by bryanbrannigan** [comment]
`pi@raspberrypi:~/ecovacs-deebot.js/example $ NODE_ENV=dev node app2.js | grep 'xml received'
[EcovacsMQTT] xml received: <ctl ret="fail" errno="0"/>
[EcovacsMQTT] xml received: <ctl ret="ok" type="Brush" left="16895" total="18000"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="DustCaseHeap" left="06095" total="7200"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="SideBrush" left="07895" total="9000"/> `

**Comment by mrbungle64** [comment]
> `pi@raspberrypi:~/ecovacs-deebot.js/example $ NODE_ENV=dev node app2.js | grep 'xml received' [EcovacsMQTT] xml received: <ctl ret="fail" errno="0"/> [EcovacsMQTT] xml received: <ctl ret="ok" type="Brush" left="16895" total="18000"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="DustCaseHeap" left="06095" total="7200"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="SideBrush" left="07895" total="9000"/> `

Thanks, but I need more data ;)

Please wait for more than 60 sec. until you receive a clean element (e.g. `<clean type="auto" speed="standard" st="h" t="841" a="17" s="1605451123" tr=""/>`)

And please comment out (or delete) line 83: ```vacbot.run('Clean');``` in `app2.js` before executing.

**Comment by bryanbrannigan** [comment]
Forgot to delete that line...

**Comment by bryanbrannigan** [comment]
`pi@raspberrypi:~/ecovacs-deebot.js/example $ NODE_ENV=dev node app2.js | grep 'xml received'
[EcovacsMQTT] xml received: <ctl ret="ok" type="Brush" left="16895" total="18000"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="SideBrush" left="07895" total="9000"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="DustCaseHeap" left="06095" total="7200"/>[EcovacsMQTT] xml received: <ctl ret="ok"><battery power="076"/></ctl>[EcovacsMQTT] xml received: <ctl ret="ok"><clean type="auto" speed="standard" mid="" p="" st="h" t="" a="" s="" tr=""/></ctl>[EcovacsMQTT] xml received: <ctl ret="ok"><charge type="SlotCharging" g="0"/></ctl>[EcovacsMQTT] xml received: <ctl ret="ok" v="2"/> `

**Comment by mrbungle64** [comment]
> `pi@raspberrypi:~/ecovacs-deebot.js/example $ NODE_ENV=dev node app2.js | grep 'xml received' [EcovacsMQTT] xml received: <ctl ret="ok" type="Brush" left="16895" total="18000"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="SideBrush" left="07895" total="9000"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="DustCaseHeap" left="06095" total="7200"/>[EcovacsMQTT] xml received: <ctl ret="ok"><battery power="076"/></ctl>[EcovacsMQTT] xml received: <ctl ret="ok"><clean type="auto" speed="standard" mid="" p="" st="h" t="" a="" s="" tr=""/></ctl>[EcovacsMQTT] xml received: <ctl ret="ok"><charge type="SlotCharging" g="0"/></ctl>[EcovacsMQTT] xml received: <ctl ret="ok" v="2"/> `

:+1: 

Can you please start auto cleaning from your mobile app and execute the example app again?

**Comment by bryanbrannigan** [comment]
`pi@raspberrypi:~/ecovacs-deebot.js/example $ NODE_ENV=dev node app2.js | grep 'xml received'
[EcovacsMQTT] xml received: <ctl ret="ok" type="SideBrush" left="07895" total="9000"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="Brush" left="16895" total="18000"/>[EcovacsMQTT] xml received: <ctl ret="ok" type="DustCaseHeap" left="06095" total="7200"/>[EcovacsMQTT] xml received: <ctl ts="1605445154" td="CleanReport"><clean type="auto" speed="standard" mid="" p="" st="s" rsn="a" a="" l="" sts=""/></ctl>[EcovacsMQTT] xml received: <ctl ts="1605445154" td="errors" new="" old=""/>[EcovacsMQTT] xml received: <ctl ts="1605434355374" td="CleanReportServer" act="s" type="auto" cs="1605416354" area="000" last="000" mapCount="000" sts="1605416354"/>
[EcovacsMQTT] xml received: <ctl ts="1605434355872" td="CleanSt" a="0000" s="0000" l="0000" t=""/>[EcovacsMQTT] xml received: <ctl td="Pos" t="p" p="200,200" a=""/>[EcovacsMQTT] xml received: <ctl ts="1605434361565" td="ChargeState"><charge type="Idle" h="0" r="b" s="1"/></ctl>[EcovacsMQTT] xml received: <ctl ts="1605445161" td="CleanReport"><clean type="auto" speed="standard" mid="" p="" st="s" rsn="a" a="" l="" sts=""/></ctl>[EcovacsMQTT] xml received: <ctl td="Pos" t="p" p="203,200" a=""/>[EcovacsMQTT] xml received: <ctl td="Pos" t="p" p="200,200" a=""/>[EcovacsMQTT] xml received: <ctl ts="1605434373681" td="MapS" i="00000" p="200201120020012001991201201120120012011991202201120220012021991203201120320012031991204200120419912042011" f="00427" o="" cs=""/>
[EcovacsMQTT] xml received: <ctl td="Pos" t="p" p="205,200" a=""/>[EcovacsMQTT] xml received: <ctl td="Pos" t="p" p="209,200" a=""/>[EcovacsMQTT] xml received: <ctl ts="1605434375299" td="MapS" i="00000" p="205201120520012051991206201120620012061991207201120720012071991208201120820012081991209201120920012091991" f="00428" o="" cs=""/>
[EcovacsMQTT] xml received: <ctl td="Pos" t="p" p="212,200" a=""/>[EcovacsMQTT] xml received: <ctl ts="1605434376898" td="MapS" i="00000" p="210201121020012101991211201121120012111991212201121220012121991213201121320012131991214201121420012141991" f="00429" o="" cs=""/>
[EcovacsMQTT] xml received: <ctl td="Pos" t="p" p="216,200" a=""/>[EcovacsMQTT] xml received: <ctl ts="1605434378519" td="MapS" i="00000" p="215201121520012151991216201121620012161991217201121720012171991218200121819912182011219200121919912192011" f="00430" o="" cs=""/>
[EcovacsMQTT] xml received: <ctl td="Pos" t="p" p="220,201" a=""/>[EcovacsMQTT] xml received: <ctl ts="1605445178" td="CleanReport"><clean type="auto" speed="standard" mid="" p="" st="p" rsn="a" a="" l="" sts=""/></ctl>[EcovacsMQTT] xml received: <ctl ret="ok"><charge type="Idle" g="0"/></ctl>[EcovacsMQTT] xml received: <ctl ret="ok"><clean type="auto" speed="standard" mid="" p="" st="p" t="" a="" s="" tr=""/></ctl>[EcovacsMQTT] xml received: <ctl ret="ok" v="2"/>[EcovacsMQTT] xml received: <ctl ret="ok"><battery power="077"/></ctl> `

**Comment by mrbungle64** [comment]
@eightzerobits 

Thank you very much :+1: 

But I cannot see a problem in this data yet ...
As far as I can see so far, it looks like it should be...

**Comment by mrbungle64** [comment]
> Clean status for Dylan : undefined

This is because the cleaning command fails.
I have to think about what we can do next to solve the problem ...

**Comment by bryanbrannigan** [comment]
Thanks I appreciate the effort.

**Comment by nicoduj** [comment]
Closing since there was no more info on this.
